name: tdmpc2
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python~=3.10.0
#  - setuptools=65.5.0
#  - wheel<0.40.0
  - pytorch=2.3.0
  - torchvision=0.18.0
  - torchaudio=2.3.0
  - pytorch-cuda=11.8